import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';
import Header from '@/components/common/header/header';
import Footer from '@/components/common/footer';

const blenderFont = localFont({
  src: [
    {
      path: '../public/fonts/BlenderPro-Thin.ttf',
      weight: '400',
      style: 'normal',
    },
    {
      path: '../public/fonts/BlenderPro-Medium.ttf',
      weight: '500',
      style: 'normal',
    },
    {
      path: '../public/fonts/BlenderPro-Book.ttf',
      weight: '600',
      style: 'normal',
    },
    {
      path: '../public/fonts/BlenderPro-Bold.ttf',
      weight: '700',
      style: 'normal',
    },
    {
      path: '../public/fonts/BlenderPro-Heavy.ttf',
      weight: '800',
      style: 'normal',
    },
  ],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${blenderFont.className} antialiased`}>
        <div className="flex flex-col min-h-screen">
          <Header />
          {children}
          <Footer />
        </div>
      </body>
    </html>
  );
}
